apps/dialog/urls.py
from django.urls import path

from dialog import views

app_name = 'dialog'

urlpatterns = [
    path('test1', views.test1, name='test1'),
    path('test2', views.test2, name='test2'),
    path('ajax', views.ajax, name='ajax'),
]

simplepro_demo/urls.py
from django.conf import settings
from django.contrib import admin
from django.http import HttpResponse
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import RedirectView

admin.site.site_title = 'SimplePro 管理后台'
admin.site.site_header = 'SimplePro 管理后台 演示'
from components import views

urlpatterns = [
                  # simplepro
                  path('sp/', include('simplepro.urls')),
                  # admin界面
                  path('admin/', admin.site.urls),
                  # 其他自定义url
                  path('dialog/', include('dialog.urls')),
                  path('area/search', views.area_search, name='area_search'),
                  # 这里可以配置网页收藏夹的图标
                  path('favicon.ico', RedirectView.as_view(url=r'static/favicon.ico')),
                  path('', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/dialog/models.py
from django.db import models

# Create your models here.
from simplepro.dialog import ModalDialog


class Dialog(models.Model):
    name = models.CharField(max_length=128, verbose_name='名称', null=True, blank=True)
    description = models.TextField(verbose_name='描述', null=True, blank=True)

    class Meta:
        verbose_name = '对话框'
        verbose_name_plural = verbose_name


    def __str__(self):
        return self.name

apps/dialog/views.py
from django.http import JsonResponse
from django.shortcuts import render

# Create your views here.
from dialog.models import Dialog


def test1(request):
    return render(request, 'dialog/test1.html')


def test2(request):
    # 这里通过request.GET可以拿到id
    pk = request.GET.get('id')
    # 然后通过id 拿到model
    dialog = Dialog.objects.get(pk=pk)
    return render(request, 'dialog/test2.html', {
        'dialog': dialog
    })


def ajax(request):
    """
    返回ajax数据
    """

    ds = []
    for i in range(30):
        name = '小红'
        if i % 2 == 0:
            name = '小明'
        ds.append({
            'value': i,
            'label': name
        })
    return JsonResponse({'ds': ds})

apps/dialog/templates/dialog/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>父页面</title>
    <!-- 引入样式 -->
    <link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-chalk/index.css">
    <!-- 引入vue -->
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.js"></script>
    <!-- 引入组件库 -->
    <script src="https://unpkg.com/element-ui/lib/index.js"></script>
</head>
<body>
<div class="main">
    {% block main %}
        这里是主要的内容区域
    {% endblock %}
</div>

{% block script %}
    脚本区域
{% endblock %}
</body>
</html>

apps/dialog/templates/dialog/test1.html
{% extends 'dialog/base.html' %}

{% block main %}

    <div>子页面对话框的内容</div>
    <div>
        获取到的ID：{{ request.GET.id }}
    </div>

    <div id="app">
        <div v-text="message"></div>
        <el-select v-model="value" placeholder="请选择">
            <el-option
                    v-for="item in options"
                    :key="item.value"
                    :label="item.label"
                    :value="item.value">
            </el-option>
        </el-select>
    </div>

{% endblock %}


{% block script %}


    <script type="text/javascript">


        //这里是vue的代码，渲染id为app的div，可以在div中加入element-ui的组件
        new Vue({
            el: '#app',
            data() {
                return {
                    message: 'Hello Vue!',
                    options: [{
                        value: '选项1',
                        label: '黄金糕'
                    }, {
                        value: '选项2',
                        label: '双皮奶'
                    }, {
                        value: '选项3',
                        label: '蚵仔煎'
                    }, {
                        value: '选项4',
                        label: '龙须面'
                    }, {
                        value: '选项5',
                        label: '北京烤鸭'
                    }],
                    value: ''
                }
            }
        })


    </script>
{% endblock %}

apps/dialog/templates/dialog/test2.html
{% extends 'dialog/base.html' %}

{% block main %}

    <div>子页面对话框的内容</div>
    <div>
        ID：{{ dialog.name }}
    </div>

    <div>
        内容：{{ dialog.description }}
    </div>

    <div>
        获取到的ID：{{ request.GET.id }}
    </div>

    <div id="app" v-loading="loading">
        <div v-text="message"></div>
        <el-select v-model="select" placeholder="请选择">
            <el-option
                    v-for="item in options"
                    :key="item.value"
                    :label="item.label"
                    :value="item.value">
            </el-option>
        </el-select>

        <div>选择的是：<span v-text="select"></span></div>


        <el-card class="box-card">
            <div slot="header" class="clearfix">
                <span>卡片名称</span>
                <el-button style="float: right; padding: 3px 0" type="text">操作按钮</el-button>
            </div>
            <div v-for="item in options">
                <span v-text="item.label"></span>
                <span v-text="item.value"></span>
            </div>
        </el-card>


        <el-button type="primary" @click="closeDialog()">点击模拟ajax请求后关闭对话框</el-button>
    </div>

{% endblock %}


{% block script %}
    {#引入axios#}
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script type="text/javascript">


        //这里是vue的代码，渲染id为app的div，可以在div中加入element-ui的组件
        new Vue({
            el: '#app',
            data() {
                return {
                    loading: false,
                    message: 'Hello Vue!',
                    options: [],
                    select: ''
                }
            },
            created() {
                let self = this;
                //异步加载数据
                self.loading = true;
                axios.get('{% url 'dialog:ajax' %}').then(res => {
                    self.options = res.data.ds;
                }).finally(() => {
                    self.loading = false;
                });
            },
            methods: {
                closeDialog() {
                    this.$message('操作成功！')
                    //刷新表格的数据
                    parent.postMessage({type: 'refresh'}, '*');

                    //关闭对话框
                    parent.postMessage({type: 'close'},'*');
                }
            }
        })


    </script>
{% endblock %}